name: Install test (React Native)

on:
  # Every day at 9:00 CET
  schedule:
    - cron: "0 8 * * *"
  # You can also activate this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      realm-version:
        description: The version of Realm to install
        required: true
        default: latest
      react-native-version:
        description: The version of React Native to install
        required: true
        default: nightly

jobs:
  install:
    runs-on: macos-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install npm v7
        run: npm install -g npm@7
      - name: Install React Native & Realm
        run: install.sh ${{ github.event.inputs.react-native-version }} ${{ github.event.inputs.realm-version }}
        working-directory: install-tests/react-native
      - name: Run the test (iOS)
        run: run-test.sh ios
        working-directory: install-tests/react-native
      - name: Run the test (Android)
        run: run-test.sh ios
        working-directory: install-tests/react-native
